title: Franks Github Pages
author: Frank Alila
email: frablazen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the new learning on Github I know I can get all this in 6 weeks flat, one step at a time.

# social links
twitter_username: frablazen # DO NOT include the @ character, or else the build will fail!
github_username:  FrankAlila # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
